#!/usr/bin/python

import sys
import os

usage = """
Usage
-----
rlencode <input_file> <output_file>

Description
-----------
'rlencode' takes a comma seperated list of 1 byte values
and applies a run length encoding. The output is a comma
seperated list of 1 byte values. Every run in the input is represented
by 4 bytes in the outbout comprising a 16 bit original index where run length started, an 8 bit run length and an 8 bit value. eg:

5, 5, 5, 5, 5, 5  ----> 0, 0, 6, 5
"""

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print usage
        exit(0)

    fi = open(sys.argv[1], 'r')
    lines = fi.readlines()
    line = "".join(lines)
    values = line.split(',')
    values = map(lambda v: v.strip(), values)
    values = filter(lambda v: v != '', values)

    fo = open(sys.argv[2], 'w')
    rlength = 1
    idx = 1
    start_idx = 0
    result = ''
    prev_value = values[0]
    for v in values[1:]: 
        if v != prev_value or rlength == 255:
            result += "%d,%d,%d,%d," % (start_idx & 255, (start_idx >> 8) & 255, rlength, int(prev_value))
            rlength = 1
            prev_value = v
            start_idx = idx
        else:
            rlength += 1
        idx += 1
           
    result += "%d,%d,%d,%d," % (start_idx & 255, (start_idx >> 8) & 255, rlength, int(prev_value))
    fo.write(result)  
